version: '2'
services:
  web:
    build: .
    command: node app.js
    volumes:
      - .:/usr/app/
    ports:
      - "80:80"
    networks:
      - backbone

networks:
    backbone:
        driver: bridge
